---
- name: Deploy Prometheus, Grafana, Alertmanager and Docker Compose
  hosts: monitoring
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker's official repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
    - name: Update package index
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
    - name: Create Prometheus, Grafana, and Alertmanager config directory
      file:
        path: /etc/prometheus
        state: directory
    - name: Create Prometheus config file
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
    - name: Create Alertmanager config file
      template:
        src: alertmanager.yml.j2
        dest: /etc/prometheus/alertmanager.yml
    - name: Create Grafana config file
      template:
        src: grafana.ini.j2
        dest: /etc/grafana/grafana.ini
    - name: Create Prometheus, Grafana, and Alertmanager compose file
      template:
        src: docker-compose.yml.j2
        dest: /etc/prometheus/docker-compose.yml
    - name: Start Prometheus, Grafana, and Alertmanager
      command: "docker-compose -f /etc/prometheus/docker-compose.yml up -d"
